// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'data_model.dart' as p0;
import 'entities/additional_fields_type.dart' as p1;
import 'entities/address.dart' as p2;
import 'entities/address_type.dart' as p3;
import 'entities/attributes.dart' as p4;
import 'entities/beneficiary_type.dart' as p5;
import 'entities/blood_group.dart' as p6;
import 'entities/boundary.dart' as p7;
import 'entities/deliver_strategy_type.dart' as p8;
import 'entities/document.dart' as p9;
import 'entities/downsync.dart' as p10;
import 'entities/facility.dart' as p11;
import 'entities/gender.dart' as p12;
import 'entities/h_f_referral.dart' as p13;
import 'entities/household.dart' as p14;
import 'entities/household_member.dart' as p15;
import 'entities/identifier.dart' as p16;
import 'entities/individual.dart' as p17;
import 'entities/locality.dart' as p18;
import 'entities/name.dart' as p19;
import 'entities/product.dart' as p20;
import 'entities/product_variant.dart' as p21;
import 'entities/project.dart' as p22;
import 'entities/project_beneficiary.dart' as p23;
import 'entities/project_facility.dart' as p24;
import 'entities/project_product_variant.dart' as p25;
import 'entities/project_resource.dart' as p26;
import 'entities/project_staff.dart' as p27;
import 'entities/project_type.dart' as p28;
import 'entities/referral.dart' as p29;
import 'entities/roles_type.dart' as p30;
import 'entities/service.dart' as p31;
import 'entities/service_attributes.dart' as p32;
import 'entities/service_definition.dart' as p33;
import 'entities/side_effect.dart' as p34;
import 'entities/status.dart' as p35;
import 'entities/stock.dart' as p36;
import 'entities/stock_reconciliation.dart' as p37;
import 'entities/target.dart' as p38;
import 'entities/task.dart' as p39;
import 'entities/task_resource.dart' as p40;
import 'entities/transaction_reason.dart' as p41;
import 'entities/transaction_type.dart' as p42;
import 'entities/user.dart' as p43;
import 'oplog/oplog_entry.dart' as p44;
import 'pgr_complaints/pgr_address.dart' as p45;
import 'pgr_complaints/pgr_complaints.dart' as p46;
import 'pgr_complaints/pgr_complaints_response.dart' as p47;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AdditionalFieldsTypeMapper.ensureInitialized();
  p2.AddressSearchModelMapper.ensureInitialized();
  p2.AddressModelMapper.ensureInitialized();
  p2.AddressAdditionalFieldsMapper.ensureInitialized();
  p3.AddressTypeMapper.ensureInitialized();
  p4.AttributesSearchModelMapper.ensureInitialized();
  p4.AttributesModelMapper.ensureInitialized();
  p4.AttributesAdditionalFieldsMapper.ensureInitialized();
  p5.BeneficiaryTypeMapper.ensureInitialized();
  p6.BloodGroupMapper.ensureInitialized();
  p7.BoundarySearchModelMapper.ensureInitialized();
  p7.BoundaryModelMapper.ensureInitialized();
  p8.DeliverStrategyTypeMapper.ensureInitialized();
  p9.DocumentSearchModelMapper.ensureInitialized();
  p9.DocumentModelMapper.ensureInitialized();
  p9.DocumentAdditionalFieldsMapper.ensureInitialized();
  p10.DownsyncSearchModelMapper.ensureInitialized();
  p10.DownsyncModelMapper.ensureInitialized();
  p10.DownsyncAdditionalFieldsMapper.ensureInitialized();
  p11.FacilitySearchModelMapper.ensureInitialized();
  p11.FacilityModelMapper.ensureInitialized();
  p11.FacilityAdditionalFieldsMapper.ensureInitialized();
  p12.GenderMapper.ensureInitialized();
  p13.HFReferralSearchModelMapper.ensureInitialized();
  p13.HFReferralModelMapper.ensureInitialized();
  p13.HFReferralAdditionalFieldsMapper.ensureInitialized();
  p14.HouseholdSearchModelMapper.ensureInitialized();
  p14.HouseholdModelMapper.ensureInitialized();
  p14.HouseholdAdditionalFieldsMapper.ensureInitialized();
  p15.HouseholdMemberSearchModelMapper.ensureInitialized();
  p15.HouseholdMemberModelMapper.ensureInitialized();
  p15.HouseholdMemberAdditionalFieldsMapper.ensureInitialized();
  p16.IdentifierSearchModelMapper.ensureInitialized();
  p16.IdentifierModelMapper.ensureInitialized();
  p16.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p17.IndividualSearchModelMapper.ensureInitialized();
  p17.IndividualModelMapper.ensureInitialized();
  p17.IndividualAdditionalFieldsMapper.ensureInitialized();
  p18.LocalitySearchModelMapper.ensureInitialized();
  p18.LocalityModelMapper.ensureInitialized();
  p18.LocalityAdditionalFieldsMapper.ensureInitialized();
  p19.NameSearchModelMapper.ensureInitialized();
  p19.NameModelMapper.ensureInitialized();
  p19.NameAdditionalFieldsMapper.ensureInitialized();
  p20.ProductSearchModelMapper.ensureInitialized();
  p20.ProductModelMapper.ensureInitialized();
  p20.ProductAdditionalFieldsMapper.ensureInitialized();
  p21.ProductVariantSearchModelMapper.ensureInitialized();
  p21.ProductVariantModelMapper.ensureInitialized();
  p21.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p22.ProjectSearchModelMapper.ensureInitialized();
  p22.ProjectModelMapper.ensureInitialized();
  p22.ProjectAdditionalFieldsMapper.ensureInitialized();
  p23.ProjectBeneficiarySearchModelMapper.ensureInitialized();
  p23.ProjectBeneficiaryModelMapper.ensureInitialized();
  p23.ProjectBeneficiaryAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectFacilitySearchModelMapper.ensureInitialized();
  p24.ProjectFacilityModelMapper.ensureInitialized();
  p24.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p25.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p25.ProjectProductVariantModelMapper.ensureInitialized();
  p25.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p26.ProjectResourceSearchModelMapper.ensureInitialized();
  p26.ProjectResourceModelMapper.ensureInitialized();
  p26.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p27.ProjectStaffSearchModelMapper.ensureInitialized();
  p27.ProjectStaffModelMapper.ensureInitialized();
  p27.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectTypeSearchModelMapper.ensureInitialized();
  p28.ProjectTypeModelMapper.ensureInitialized();
  p28.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p29.ReferralSearchModelMapper.ensureInitialized();
  p29.ReferralModelMapper.ensureInitialized();
  p29.ReferralAdditionalFieldsMapper.ensureInitialized();
  p30.RolesTypeMapper.ensureInitialized();
  p31.ServiceSearchModelMapper.ensureInitialized();
  p31.ServiceModelMapper.ensureInitialized();
  p31.ServiceAdditionalFieldsMapper.ensureInitialized();
  p32.ServiceAttributesSearchModelMapper.ensureInitialized();
  p32.ServiceAttributesModelMapper.ensureInitialized();
  p32.ServiceAttributesAdditionalFieldsMapper.ensureInitialized();
  p33.ServiceDefinitionSearchModelMapper.ensureInitialized();
  p33.ServiceDefinitionModelMapper.ensureInitialized();
  p33.ServiceDefinitionAdditionalFieldsMapper.ensureInitialized();
  p34.SideEffectSearchModelMapper.ensureInitialized();
  p34.SideEffectModelMapper.ensureInitialized();
  p34.SideEffectAdditionalFieldsMapper.ensureInitialized();
  p35.StatusMapper.ensureInitialized();
  p36.StockSearchModelMapper.ensureInitialized();
  p36.StockModelMapper.ensureInitialized();
  p36.StockAdditionalFieldsMapper.ensureInitialized();
  p37.StockReconciliationSearchModelMapper.ensureInitialized();
  p37.StockReconciliationModelMapper.ensureInitialized();
  p37.StockReconciliationAdditionalFieldsMapper.ensureInitialized();
  p38.TargetSearchModelMapper.ensureInitialized();
  p38.TargetModelMapper.ensureInitialized();
  p38.TargetAdditionalFieldsMapper.ensureInitialized();
  p39.TaskSearchModelMapper.ensureInitialized();
  p39.TaskModelMapper.ensureInitialized();
  p39.TaskAdditionalFieldsMapper.ensureInitialized();
  p40.TaskResourceSearchModelMapper.ensureInitialized();
  p40.TaskResourceModelMapper.ensureInitialized();
  p40.TaskResourceAdditionalFieldsMapper.ensureInitialized();
  p41.TransactionReasonMapper.ensureInitialized();
  p42.TransactionTypeMapper.ensureInitialized();
  p43.UserSearchModelMapper.ensureInitialized();
  p43.UserModelMapper.ensureInitialized();
  p43.UserAdditionalFieldsMapper.ensureInitialized();
  p44.OpLogEntryMapper.ensureInitialized();
  p44.AdditionalIdMapper.ensureInitialized();
  p44.DataOperationMapper.ensureInitialized();
  p44.ApiOperationMapper.ensureInitialized();
  p45.PgrAddressModelMapper.ensureInitialized();
  p45.GeoLocationMapper.ensureInitialized();
  p46.PgrComplaintModelMapper.ensureInitialized();
  p46.PgrComplainantModelMapper.ensureInitialized();
  p46.PgrRolesModelMapper.ensureInitialized();
  p46.PgrServiceSearchModelMapper.ensureInitialized();
  p46.PgrServiceModelMapper.ensureInitialized();
  p46.PgrWorkflowModelMapper.ensureInitialized();
  p46.PgrFiltersMapper.ensureInitialized();
  p46.PgrSearchKeysMapper.ensureInitialized();
  p46.PgrAdditionalDetailsMapper.ensureInitialized();
  p46.PgrServiceApplicationStatusMapper.ensureInitialized();
  p47.PgrServiceCreateResponseModelMapper.ensureInitialized();
  p47.PgrComplaintResponseModelMapper.ensureInitialized();
  p47.PgrComplainantResponseModelMapper.ensureInitialized();
  p47.PgrServiceResponseModelMapper.ensureInitialized();
}
