// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element

import 'data_model.dart' as p0;
import 'entities/additional_fields_type.dart' as p1;
import 'entities/address.dart' as p2;
import 'entities/address_type.dart' as p3;
import 'entities/attributes.dart' as p4;
import 'entities/beneficiary_type.dart' as p5;
import 'entities/blood_group.dart' as p6;
import 'entities/boundary.dart' as p7;
import 'entities/deliver_strategy_type.dart' as p8;
import 'entities/document.dart' as p9;
import 'entities/downsync.dart' as p10;
import 'entities/facility.dart' as p11;
import 'entities/gender.dart' as p12;
import 'entities/hcm_attendance_log_model.dart' as p13;
import 'entities/hcm_attendance_model.dart' as p14;
import 'entities/household.dart' as p15;
import 'entities/household_member.dart' as p16;
import 'entities/identifier.dart' as p17;
import 'entities/individual.dart' as p18;
import 'entities/locality.dart' as p19;
import 'entities/name.dart' as p20;
import 'entities/product.dart' as p21;
import 'entities/product_variant.dart' as p22;
import 'entities/project.dart' as p23;
import 'entities/project_beneficiary.dart' as p24;
import 'entities/project_facility.dart' as p25;
import 'entities/project_product_variant.dart' as p26;
import 'entities/project_resource.dart' as p27;
import 'entities/project_staff.dart' as p28;
import 'entities/project_type.dart' as p29;
import 'entities/referral.dart' as p30;
import 'entities/roles.dart' as p31;
import 'entities/roles_type.dart' as p32;
import 'entities/scanner_type.dart' as p33;
import 'entities/service.dart' as p34;
import 'entities/service_attributes.dart' as p35;
import 'entities/service_definition.dart' as p36;
import 'entities/side_effect.dart' as p37;
import 'entities/status.dart' as p38;
import 'entities/stock.dart' as p39;
import 'entities/stock_reconciliation.dart' as p40;
import 'entities/target.dart' as p41;
import 'entities/task.dart' as p42;
import 'entities/task_resource.dart' as p43;
import 'entities/transaction_reason.dart' as p44;
import 'entities/transaction_type.dart' as p45;
import 'entities/user.dart' as p46;
import 'oplog/oplog_entry.dart' as p47;
import 'pgr_complaints/pgr_address.dart' as p48;
import 'pgr_complaints/pgr_complaints.dart' as p49;
import 'pgr_complaints/pgr_complaints_response.dart' as p50;
import 'package:attendance_management/models/attendance_audit.dart' as p51;
import 'package:attendance_management/models/staff.dart' as p52;
import 'package:attendance_management/models/attendee.dart' as p53;
import 'package:attendance_management/models/attendance_log.dart' as p54;
import 'package:attendance_management/models/attendance_register.dart' as p55;

void initializeMappers() {
  p0.EntityModelMapper.ensureInitialized();
  p0.EntitySearchModelMapper.ensureInitialized();
  p0.AdditionalFieldsMapper.ensureInitialized();
  p0.AdditionalFieldMapper.ensureInitialized();
  p0.ClientAuditDetailsMapper.ensureInitialized();
  p0.AuditDetailsMapper.ensureInitialized();
  p1.AdditionalFieldsTypeMapper.ensureInitialized();
  p2.AddressSearchModelMapper.ensureInitialized();
  p2.AddressModelMapper.ensureInitialized();
  p2.AddressAdditionalFieldsMapper.ensureInitialized();
  p3.AddressTypeMapper.ensureInitialized();
  p4.AttributesSearchModelMapper.ensureInitialized();
  p4.AttributesModelMapper.ensureInitialized();
  p4.AttributesAdditionalFieldsMapper.ensureInitialized();
  p5.BeneficiaryTypeMapper.ensureInitialized();
  p6.BloodGroupMapper.ensureInitialized();
  p7.BoundarySearchModelMapper.ensureInitialized();
  p7.BoundaryModelMapper.ensureInitialized();
  p8.DeliverStrategyTypeMapper.ensureInitialized();
  p9.DocumentSearchModelMapper.ensureInitialized();
  p9.DocumentModelMapper.ensureInitialized();
  p9.DocumentAdditionalFieldsMapper.ensureInitialized();
  p10.DownsyncSearchModelMapper.ensureInitialized();
  p10.DownsyncModelMapper.ensureInitialized();
  p10.DownsyncAdditionalFieldsMapper.ensureInitialized();
  p11.FacilitySearchModelMapper.ensureInitialized();
  p11.FacilityModelMapper.ensureInitialized();
  p11.FacilityAdditionalFieldsMapper.ensureInitialized();
  p12.GenderMapper.ensureInitialized();
  p13.HCMAttendanceLogSearchModelMapper.ensureInitialized();
  p13.HCMAttendanceLogModelMapper.ensureInitialized();
  p14.HCMAttendanceSearchModelMapper.ensureInitialized();
  p14.HCMAttendanceRegisterModelMapper.ensureInitialized();
  p14.HCMAttendanceAdditionalModelMapper.ensureInitialized();
  p15.HouseholdSearchModelMapper.ensureInitialized();
  p15.HouseholdModelMapper.ensureInitialized();
  p15.HouseholdAdditionalFieldsMapper.ensureInitialized();
  p16.HouseholdMemberSearchModelMapper.ensureInitialized();
  p16.HouseholdMemberModelMapper.ensureInitialized();
  p16.HouseholdMemberAdditionalFieldsMapper.ensureInitialized();
  p17.IdentifierSearchModelMapper.ensureInitialized();
  p17.IdentifierModelMapper.ensureInitialized();
  p17.IdentifierAdditionalFieldsMapper.ensureInitialized();
  p18.IndividualSearchModelMapper.ensureInitialized();
  p18.IndividualModelMapper.ensureInitialized();
  p18.IndividualAdditionalFieldsMapper.ensureInitialized();
  p19.LocalitySearchModelMapper.ensureInitialized();
  p19.LocalityModelMapper.ensureInitialized();
  p19.LocalityAdditionalFieldsMapper.ensureInitialized();
  p20.NameSearchModelMapper.ensureInitialized();
  p20.NameModelMapper.ensureInitialized();
  p20.NameAdditionalFieldsMapper.ensureInitialized();
  p21.ProductSearchModelMapper.ensureInitialized();
  p21.ProductModelMapper.ensureInitialized();
  p21.ProductAdditionalFieldsMapper.ensureInitialized();
  p22.ProductVariantSearchModelMapper.ensureInitialized();
  p22.ProductVariantModelMapper.ensureInitialized();
  p22.ProductVariantAdditionalFieldsMapper.ensureInitialized();
  p23.ProjectSearchModelMapper.ensureInitialized();
  p23.ProjectModelMapper.ensureInitialized();
  p23.ProjectAdditionalFieldsMapper.ensureInitialized();
  p24.ProjectBeneficiarySearchModelMapper.ensureInitialized();
  p24.ProjectBeneficiaryModelMapper.ensureInitialized();
  p24.ProjectBeneficiaryAdditionalFieldsMapper.ensureInitialized();
  p25.ProjectFacilitySearchModelMapper.ensureInitialized();
  p25.ProjectFacilityModelMapper.ensureInitialized();
  p25.ProjectFacilityAdditionalFieldsMapper.ensureInitialized();
  p26.ProjectProductVariantSearchModelMapper.ensureInitialized();
  p26.ProjectProductVariantModelMapper.ensureInitialized();
  p26.ProjectProductVariantAdditionalFieldsMapper.ensureInitialized();
  p27.ProjectResourceSearchModelMapper.ensureInitialized();
  p27.ProjectResourceModelMapper.ensureInitialized();
  p27.ProjectResourceAdditionalFieldsMapper.ensureInitialized();
  p28.ProjectStaffSearchModelMapper.ensureInitialized();
  p28.ProjectStaffModelMapper.ensureInitialized();
  p28.ProjectStaffAdditionalFieldsMapper.ensureInitialized();
  p29.ProjectTypeSearchModelMapper.ensureInitialized();
  p29.ProjectTypeModelMapper.ensureInitialized();
  p29.ProjectTypeAdditionalFieldsMapper.ensureInitialized();
  p30.ReferralSearchModelMapper.ensureInitialized();
  p30.ReferralModelMapper.ensureInitialized();
  p30.ReferralAdditionalFieldsMapper.ensureInitialized();
  p31.RolesMapper.ensureInitialized();
  p32.RolesTypeMapper.ensureInitialized();
  p33.ScannerTypeMapper.ensureInitialized();
  p34.ServiceSearchModelMapper.ensureInitialized();
  p34.ServiceModelMapper.ensureInitialized();
  p34.ServiceAdditionalFieldsMapper.ensureInitialized();
  p35.ServiceAttributesSearchModelMapper.ensureInitialized();
  p35.ServiceAttributesModelMapper.ensureInitialized();
  p35.ServiceAttributesAdditionalFieldsMapper.ensureInitialized();
  p36.ServiceDefinitionSearchModelMapper.ensureInitialized();
  p36.ServiceDefinitionModelMapper.ensureInitialized();
  p36.ServiceDefinitionAdditionalFieldsMapper.ensureInitialized();
  p37.SideEffectSearchModelMapper.ensureInitialized();
  p37.SideEffectModelMapper.ensureInitialized();
  p37.SideEffectAdditionalFieldsMapper.ensureInitialized();
  p38.StatusMapper.ensureInitialized();
  p39.StockSearchModelMapper.ensureInitialized();
  p39.StockModelMapper.ensureInitialized();
  p39.StockAdditionalFieldsMapper.ensureInitialized();
  p40.StockReconciliationSearchModelMapper.ensureInitialized();
  p40.StockReconciliationModelMapper.ensureInitialized();
  p40.StockReconciliationAdditionalFieldsMapper.ensureInitialized();
  p41.TargetSearchModelMapper.ensureInitialized();
  p41.TargetModelMapper.ensureInitialized();
  p41.TargetAdditionalFieldsMapper.ensureInitialized();
  p42.TaskSearchModelMapper.ensureInitialized();
  p42.TaskModelMapper.ensureInitialized();
  p42.TaskAdditionalFieldsMapper.ensureInitialized();
  p43.TaskResourceSearchModelMapper.ensureInitialized();
  p43.TaskResourceModelMapper.ensureInitialized();
  p43.TaskResourceAdditionalFieldsMapper.ensureInitialized();
  p44.TransactionReasonMapper.ensureInitialized();
  p45.TransactionTypeMapper.ensureInitialized();
  p46.UserSearchModelMapper.ensureInitialized();
  p46.UserModelMapper.ensureInitialized();
  p46.UserAdditionalFieldsMapper.ensureInitialized();
  p47.OpLogEntryMapper.ensureInitialized();
  p47.AdditionalIdMapper.ensureInitialized();
  p47.DataOperationMapper.ensureInitialized();
  p47.ApiOperationMapper.ensureInitialized();
  p48.PgrAddressModelMapper.ensureInitialized();
  p48.GeoLocationMapper.ensureInitialized();
  p49.PgrComplaintModelMapper.ensureInitialized();
  p49.PgrComplainantModelMapper.ensureInitialized();
  p49.PgrRolesModelMapper.ensureInitialized();
  p49.PgrServiceSearchModelMapper.ensureInitialized();
  p49.PgrServiceModelMapper.ensureInitialized();
  p49.PgrWorkflowModelMapper.ensureInitialized();
  p49.PgrFiltersMapper.ensureInitialized();
  p49.PgrSearchKeysMapper.ensureInitialized();
  p49.PgrAdditionalDetailsMapper.ensureInitialized();
  p49.PgrServiceApplicationStatusMapper.ensureInitialized();
  p50.PgrServiceCreateResponseModelMapper.ensureInitialized();
  p50.PgrComplaintResponseModelMapper.ensureInitialized();
  p50.PgrComplainantResponseModelMapper.ensureInitialized();
  p50.PgrServiceResponseModelMapper.ensureInitialized();
p51.AttendanceAuditDetailsMapper.ensureInitialized();
p52.StaffModelMapper.ensureInitialized();
p53.AttendeeModelMapper.ensureInitialized();
p54.AttendanceLogModelMapper.ensureInitialized();
p55.AttendanceRegisterModelMapper.ensureInitialized();
}
