name: custom_text_field
description: A Custom Reactive form Text field.
version: 1.0.0
homepage: https://github.com/Ramkrishna-egov/health-campaign-field-worker-app/tree/master/custom_text_field

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  reactive_forms: ^14.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
